services:
############################## PROXY ########################################
  opencdmp.proxy:
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '1'
        reservations:
          memory: 128M
          cpus: '0.5'
    memswap_limit: 512M
    ports:
      - "0.0.0.0:${PROXY_APP_PORT}:8081"
    volumes:
      - ${CONFIG_FILES_PATH}/proxy/nginx.conf:/etc/nginx/nginx.conf
      - ${CONFIG_FILES_PATH}/proxy/ProxyNginx.conf:/etc/nginx/conf.d/default.conf
      - ${LOG_FILES_PATH}/proxy:/tmp/logs
    networks:
      - opencdmp-proxy-network

############################## OPENCDMP APP #################################
  opencdmp.backend:
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 2048M
          cpus: '1'
        reservations:
          memory: 1024M
          cpus: '0.5'
    memswap_limit: 4096M
    environment:
      - PROFILE=${PROFILE}
    expose:
      - "8080"
    volumes:
      - ${CONFIG_FILES_PATH}/opencdmp/backend/config:/config
      - ${CONFIG_FILES_PATH}/opencdmp/backend/i18n:/i18n
      - ${CONFIG_FILES_PATH}/opencdmp/backend/material:/material
      - ${STORAGE_PATH}/opencdmp/backend:/storage
      - ${LOG_FILES_PATH}/opencdmp/backend:/logs
    networks:
      - opencdmp-proxy-network
      - opencdmp-backend-network

  opencdmp.frontend:
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 2048M
          cpus: '1'
        reservations:
          memory: 1024M
          cpus: '0.5'
    memswap_limit: 4096M
    expose:
      - "8080"
    environment:
      - WEBAPP_API_URL=${WEBAPP_API_URL}
      - INSTALLATION_URL=${INSTALLATION_URL}
      - DEFAULT_CULTURE=${DEFAULT_CULTURE}
      - KEYCLOAK_ADDRESS=${KEYCLOAK_ADDRESS}
      - KEYCLOAK_REALM=${KEYCLOAK_REALM}
      - KEYCLOAK_CLIENT_ID=${KEYCLOAK_CLIENT_ID}
      - KEYCLOAK_SCOPE=${KEYCLOAK_SCOPE}
      - KPI_SERVICE_ENABLED=${KPI_SERVICE_ENABLED}
      - ACCOUNTING_SERVICE_ENABLED=${ACCOUNTING_SERVICE_ENABLED}
      - LOGGING_ENABLED=${LOGGING_ENABLED}
    volumes:
      # - ${CONFIG_FILES_PATH}/opencdmp/frontend/config-override.json:/usr/share/nginx/html/assets/config/config-override.json
      - ${CONFIG_FILES_PATH}/opencdmp/frontend/nginx.conf:/etc/nginx/nginx.conf
      - ${CONFIG_FILES_PATH}/opencdmp/frontend/WebAppNginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - opencdmp-proxy-network

  opencdmp.notification:
    deploy:
      resources:
        limits:
          memory: 1024M
          cpus: '1'
        reservations:
          memory: 512M
          cpus: '0.5'
    memswap_limit: 2048M
    restart: unless-stopped
    expose:
      - "8080"
    environment:
      - PROFILE=${PROFILE}
    volumes:
      - ${CONFIG_FILES_PATH}/opencdmp/notification/config:/config
      - ${CONFIG_FILES_PATH}/opencdmp/notification/messages:/messages
      - ${CONFIG_FILES_PATH}/opencdmp/notification/notification_templates:/notification_templates
      - ${LOG_FILES_PATH}/opencdmp/notification:/logs
    networks:
      - opencdmp-proxy-network
      - opencdmp-backend-network

  opencdmp.annotation:
    deploy:
      resources:
        limits:
          memory: 1024M
          cpus: '1'
        reservations:
          memory: 512M
          cpus: '0.5'
    memswap_limit: 2048M
    restart: unless-stopped
    expose:
      - "8080"
    environment:
      - PROFILE=${PROFILE}
    volumes:
      - ${CONFIG_FILES_PATH}/opencdmp/annotation/config:/config
      - ${CONFIG_FILES_PATH}/opencdmp/annotation/messages:/messages
      - ${LOG_FILES_PATH}/opencdmp/annotation:/logs
    networks:
      - opencdmp-proxy-network
      - opencdmp-backend-network

# # ############################## FILE-TRANSFORMER #################################

  opencdmp.file.transformer.docx:
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '1'
        reservations:
          memory: 128M
          cpus: '0.5'
    memswap_limit: 512M
    expose:
      - "8080"
    environment:
      - SERVER_PORT=${SERVER_PORT}
      - PROFILE=${PROFILE}
    volumes:
      - ${CONFIG_FILES_PATH}/opencdmp/file-transformer-docx/config:/config
      - ${LOG_FILES_PATH}/opencdmp/file-transformer-docx:/logs
      # - ${STORAGE_PATH}/opencdmp/file-transformer-docx:/storage
    networks:
      - opencdmp-backend-network

  opencdmp.file.transformer.rdajson:
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '1'
        reservations:
          memory: 128M
          cpus: '0.5'
    memswap_limit: 512M
    expose:
      - "8080"
    environment:
      - SERVER_PORT=${SERVER_PORT}
      - PROFILE=${PROFILE}
    volumes:
      - ${CONFIG_FILES_PATH}/opencdmp/file-transformer-rda-json/config:/config
      - ${CONFIG_FILES_PATH}/opencdmp/file-transformer-rda-json/internal:/internal
      - ${LOG_FILES_PATH}/opencdmp/file-transformer-rda-json:/logs
      # - ${STORAGE_PATH}/opencdmp/file-transformer-rda-json:/storage
    networks:
      - opencdmp-backend-network

###################################### EVALUATOR ##############################################

  opencdmp.evaluator:
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '1'
        reservations:
          memory: 128M
          cpus: '0.5'
    memswap_limit: 512M
    expose:
      - "8080"
    environment:
      - SERVER_PORT=${SERVER_PORT}
      - PROFILE=${PROFILE}
    volumes:
      - ${CONFIG_FILES_PATH}/opencdmp/evaluator-rda-madmp/config:/config
      - ${LOG_FILES_PATH}/opencdmp/evaluator-rda-madmp:/logs
    networks:
      - opencdmp-backend-network

# ############################## ZENODO #######################################
  opencdmp.zenodo:
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '1'
        reservations:
          memory: 128M
          cpus: '0.5'
    memswap_limit: 512M
    expose:
      - "8080"
    environment:
      - PROFILE=${PROFILE}
    volumes:
      - ${CONFIG_FILES_PATH}/opencdmp/zenodo/config:/config
      - ${LOG_FILES_PATH}/opencdmp/zenodo:/logs
    networks:
      - opencdmp-backend-network

################################# POSTGRES ####################################

  opencdmp.postgres:
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 2048M
          cpus: '1'
        reservations:
          memory: 1024M
          cpus: '0.5'
    memswap_limit: 4096M
    ports:
      - "0.0.0.0:${POSTGRES_PORT}:5432"
    env_file:
      - ${CONFIG_FILES_PATH}/postgres/postgres.env
    volumes:
      - ${STORAGE_PATH}/postgres/data:/var/lib/postgresql/data
      - ${CONFIG_FILES_PATH}/postgres/init-scripts:/docker-entrypoint-initdb.d
    networks:
      - opencdmp-backend-network
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U postgres -d opencdmp'"]
      interval: 15s
      timeout: 60s
      retries: 5

################################# ELASTICSEARCH #################################################
  opencdmp.elasticsearch.setup:
    user: "0"
    env_file:
      - ${CONFIG_FILES_PATH}/elk/elk.env
    environment:
      - ELASTIC_PASSWORD=elastic
    volumes:
      - ${CONFIG_FILES_PATH}/elk/elasticsearch/index_init.sh:/usr/share/elasticsearch/config/index_init.sh
    command: >
      bash -c '
        if [ x${ELASTIC_PASSWORD} == x ]; then
          echo "Set the ELASTIC_PASSWORD environment variable in the .env file";
          exit 1;
        fi;
        echo "Setting file permissions"
        chown -R root:root /usr/share/elasticsearch/config/index_init.sh;
        chmod 744 /usr/share/elasticsearch/config/index_init.sh;
        echo "Waiting for Elasticsearch availability";
        until curl -s http://opencdmp.elasticsearch:9200 | grep -q "missing authentication credentials"; do sleep 30; done;
        /usr/share/elasticsearch/config/index_init.sh;
        echo "All done!";
      '
    networks:
      - opencdmp-backend-network

  opencdmp.elasticsearch:
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 2048M
          cpus: '2'
        reservations:
          memory: 1024M
          cpus: '1'
    memswap_limit: 4096M
    env_file:
      - ${CONFIG_FILES_PATH}/elk/elk.env
    environment:
      - ES_JAVA_OPTS=-Xmx2g -Xms2g
    ulimits:
      nproc: 65535
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ${CONFIG_FILES_PATH}/elk/elasticsearch/log4j2.properties:/usr/share/elasticsearch/config/log4j2.properties:ro
      - ${CONFIG_FILES_PATH}/elk/elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
      - ${STORAGE_PATH}/elasticsearch/plugins:/usr/share/elasticsearch/plugins
      - ${STORAGE_PATH}/elasticsearch:/usr/share/elasticsearch/data
      - ${LOG_FILES_PATH}/elasticsearch:/usr/share/elasticsearch/logs
    expose:
      - "9200"
    networks:
      - opencdmp-backend-network
    healthcheck:
      test: curl -s http://localhost:9200 >/dev/null; if [[ $$? == 52 ]]; then echo 0; else echo 1; fi
      interval: 30s
      timeout: 10s
      retries: 5

#################################### KEYCLOAK ###############################################
  opencdmp.keycloak:
    restart: unless-stopped
    command: ["start-dev", "--log=console,file", "--log-file=/tmp/logs/keycloak.log", "--import-realm"]
    deploy:
      resources:
        limits:
          memory: 2048M
          cpus: '1'
        reservations:
          memory: 1024M
          cpus: '0.5'
    memswap_limit: 4096M
    env_file:
      - ${CONFIG_FILES_PATH}/keycloak/keycloak.env
    environment:
      - JAVA_OPTS_APPEND="-Djava.net.preferIPv4Stack=true"
    volumes:
      - ${LOG_FILES_PATH}/keycloak:/tmp/logs
      - ${CONFIG_FILES_PATH}/keycloak/user_init.sh:/tmp/user_init.sh
      - ${CONFIG_FILES_PATH}/keycloak/health-check.sh:/tmp/health-check.sh
      - ${CONFIG_FILES_PATH}/keycloak/imports/OpenCDMP-realm.json:/opt/keycloak/data/import/OpenCDMP-realm.json
    expose:
      - "8080"
    healthcheck:
      test: curl -s http://localhost:8080/realms/master >/dev/null; if [[ $$? == 52 ]]; then echo 0; else echo 1; fi
      interval: 30s
      retries: 5
      timeout: 10s
    networks:
      - opencdmp-proxy-network
      - opencdmp-backend-network

################################# RABBITMQ ###############################################
  opencdmp.rabbitmq:
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '1'
        reservations:
          memory: 256M
          cpus: '0.5'
    memswap_limit: 1024M
    restart: unless-stopped
    expose:
      - "5672"
    env_file:
      - ${CONFIG_FILES_PATH}/rabbitmq/rabbitmq.env
    volumes:
      - ${STORAGE_PATH}/rabbitmq:/var/lib/rabbitmq/mnesia
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3
    networks:
      - opencdmp-backend-network

################################# PDF SERVICE ##############################################
  opencdmp.pdf-service:
    deploy:
      resources:
        limits:
          memory: 2048M
          cpus: '1'
        reservations:
          memory: 1024M
          cpus: '0.5'
    memswap_limit: 4096M
    restart: unless-stopped
    expose:
     - "3000"
    hostname: pdf-service
    networks:
      - opencdmp-backend-network

networks:
  opencdmp-proxy-network:
  opencdmp-backend-network: